apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress-auths
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  rules:
    - host: magic-cloud-auths.info
      http:
        paths:
          - path: /register
            pathType: Prefix
            backend:
              service:
                name: magic-cloud-back
                port:
                  number: 8080
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: magic-cloud-back
                port:
                  number: 8080
