apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: paulinedav/custom-postgres:10.1 # Using the custom image
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret # Secrets for PostgreSQL environment variables
            - configMapRef:
                name: postgres-config # ConfigMap for additional environment variables
          volumeMounts:
            - mountPath: /var/lib/postgresql/data # Persistent volume for database data
              name: postgredb
      volumes:
        - name: postgredb
          #persistentVolumeClaim:
            #claimName: postgres-pv-claim
          emptyDir: {}