name: CI
on: [workflow_dispatch, pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Start Kubernetes minikube
        uses: medyagh/setup-minikube@master
        with:
          minikube_start_options: '--driver=docker'
      - name: Try the Kubernetes cluster
        run: kubectl get nodes
      - name: Build and test
        working-directory: . 
        run: |
          export SHELL=/bin/bash
          ./gradlew build
          docker build -f ./Dockerfile -t magic-cloud-back .
          docker images
      - name: Load Docker image into Minikube
        run: |
          minikube image load magic-cloud-back
      - name: Deploy the image to minikube
        run: |
          kubectl apply -f deployment.yml
      - name: Get Kubernetes service URL
        run: |
          kubectl get pods
          kubectl wait --for=condition=Ready pod -l app=magic-cloud-back --timeout=60s
          kubectl get pods
          minikube service list
          minikube service magic-cloud-back --url
          echo "------------------opening the service------------------"
      - name: Test Kubernetes service URL
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 10
          max_attempts: 4
          command: curl $(minikube service magic-cloud-back --url)/Hello
      - name: Log Kubernetes pods
        run: |
          kubectl logs $(kubectl get pods -l app=magic-cloud-back -o name)
